apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service2
  description: |
    A service .
  annotations:
    circleci.com/project-slug: RoadieHQ/sample-service
    github.com/project-slug: RoadieHQ/sample-service
    backstage.io/github-actions-id: RoadieHQ/sample-service
    backstage.io/aws-lambda: "HelloWorld"
spec:
  type: service
  owner: david@roadie.io
  lifecycle: experimental
